#!/bin/bash

# ===========================================
# 📊 ShadowRecon Report Generator (Markdown)
# ===========================================

target=$1
loot_dir="loot/$target"
report="$loot_dir/report.md"
timestamp=$(date '+%Y-%m-%d %H:%M:%S')

echo "[*] [Report] Building final report for $target..."
> "$report"

# === Header ===
cat <<EOF >> "$report"
# 🕵️ ShadowRecon Report: \`$target\`

**Generated on**: $timestamp  
**Tool Version**: ShadowRecon v1.0 (Bash Edition)  
**Author**: bruhh 🧠

---

EOF

# === Helper Function ===
append_section() {
  local title="$1"
  local file="$2"
  local limit="$3"

  if [[ -s "$file" ]]; then
    echo -e "## $title\n\`\`\`" >> "$report"
    if [[ "$limit" == "head" ]]; then
      head -n 20 "$file" >> "$report"
      echo "...(truncated)" >> "$report"
    else
      cat "$file" >> "$report"
    fi
    echo -e "\`\`\`\n" >> "$report"
  fi
}

# === Modules to Append ===
append_section "🌐 Subdomains" "$loot_dir/subdomains.txt"
append_section "📧 Emails & IDs" "$loot_dir/emails.txt"
append_section "📂 Archived URLs (Wayback)" "$loot_dir/wayback_urls.txt" head
append_section "🔧 JS Endpoints" "$loot_dir/js_endpoints.txt"
append_section "🐙 GitHub Leaks" "$loot_dir/github_leaks.txt"
append_section "🧬 Metadata from Public Files" "$loot_dir/metadata.txt"

# === Footer ===
cat <<EOF >> "$report"
---

> ⚔️ Report generated by **ShadowRecon**  
> Stay stealthy. Stay savage. 🧠💀  
EOF

echo "[✓] Report generated."
echo "[+] Markdown path: $report"
